// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgTivzZmHOjOSUXdUr8DqjOjdXl4Jq2CI',
    appId: '1:161027565750:web:0ae9f87409bd27cb5ade17',
    messagingSenderId: '161027565750',
    projectId: 'devfast-2022',
    authDomain: 'devfast-2022.firebaseapp.com',
    storageBucket: 'devfast-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMt_e3ZDh666zlwk4Aa7hfN_M1kHOCjnU',
    appId: '1:161027565750:android:db40dee473c8f7635ade17',
    messagingSenderId: '161027565750',
    projectId: 'devfast-2022',
    storageBucket: 'devfast-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1S8V9evLxbbYtlhDKb1bVXBP0bu-wAQI',
    appId: '1:161027565750:ios:74b6d7fdacc1bf8e5ade17',
    messagingSenderId: '161027565750',
    projectId: 'devfast-2022',
    storageBucket: 'devfast-2022.appspot.com',
    iosClientId: '161027565750-5669k0nj9lkjkissbkdfc17fu1ka6051.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1S8V9evLxbbYtlhDKb1bVXBP0bu-wAQI',
    appId: '1:161027565750:ios:74b6d7fdacc1bf8e5ade17',
    messagingSenderId: '161027565750',
    projectId: 'devfast-2022',
    storageBucket: 'devfast-2022.appspot.com',
    iosClientId: '161027565750-5669k0nj9lkjkissbkdfc17fu1ka6051.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled5',
  );
}
